/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AAAALanzador;

import LlenandoPiscinas.*;
import CodigosDeBarras.*;

/**
 *
 * @author maxxi
 */
public class AAAInicio extends javax.swing.JFrame {

    
    public AAAInicio() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltitulo2 = new javax.swing.JLabel();
        jLabelcursoacademico = new javax.swing.JLabel();
        jLabeltitulo = new javax.swing.JLabel();
        jLabeletsiinf = new javax.swing.JLabel();
        jLabeltutor = new javax.swing.JLabel();
        jLabelGRADO = new javax.swing.JLabel();
        jLabelautor = new javax.swing.JLabel();
        jButtonDOCUMENTACION = new javax.swing.JButton();
        jButtonPROBLEMAS = new javax.swing.JButton();
        jLabeltfg = new javax.swing.JLabel();
        jLabelENCABEZADO = new javax.swing.JLabel();
        jLabelFONDO_IZQ = new javax.swing.JLabel();
        jLabelFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1030, 600));
        setMinimumSize(new java.awt.Dimension(1030, 600));
        setPreferredSize(new java.awt.Dimension(1030, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitulo2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabeltitulo2.setText("PARA LA ENSEÑANZA DE LA PROGRAMACIÓN");
        getContentPane().add(jLabeltitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        jLabelcursoacademico.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelcursoacademico.setText("CURSO ACADÉMICO 2017/2018");
        getContentPane().add(jLabelcursoacademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jLabeltitulo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabeltitulo.setText("CONCURSOS DE PROGRAMACIÓN ");
        getContentPane().add(jLabeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jLabeletsiinf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeletsiinf.setText("ETS DE INGENIEROS INFORMÁTICOS");
        getContentPane().add(jLabeletsiinf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabeltutor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeltutor.setText("TUTOR: CLARA BENAC EARLE");
        getContentPane().add(jLabeltutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, -1));

        jLabelGRADO.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelGRADO.setText("GRADO EN MATEMÁTICAS E INFORMÁTICA");
        getContentPane().add(jLabelGRADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 900, 70));

        jLabelautor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelautor.setText("AUTOR: ISMAEL MORENO MECHBAL");
        getContentPane().add(jLabelautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        jButtonDOCUMENTACION.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDOCUMENTACION.setForeground(new java.awt.Color(0, 153, 153));
        jButtonDOCUMENTACION.setText("Documentación");
        jButtonDOCUMENTACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDOCUMENTACIONActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDOCUMENTACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 40));

        jButtonPROBLEMAS.setBackground(new java.awt.Color(204, 204, 204));
        jButtonPROBLEMAS.setForeground(new java.awt.Color(0, 153, 153));
        jButtonPROBLEMAS.setText("Problemas");
        jButtonPROBLEMAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPROBLEMASActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPROBLEMAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        jLabeltfg.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabeltfg.setText("TRABAJO DE FIN DE GRADO");
        getContentPane().add(jLabeltfg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 490, 70));

        jLabelENCABEZADO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde oscuro.jpg"))); // NOI18N
        getContentPane().add(jLabelENCABEZADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jLabelFONDO_IZQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde clarito.jpg"))); // NOI18N
        getContentPane().add(jLabelFONDO_IZQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 740, 60));
        getContentPane().add(jLabelFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPROBLEMASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPROBLEMASActionPerformed
        // TODO add your handling code here:
        Problemas a= new Problemas();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPROBLEMASActionPerformed

    private void jButtonDOCUMENTACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDOCUMENTACIONActionPerformed
        // TODO add your handling code here:
        Documentacion a= new Documentacion();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDOCUMENTACIONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AAAInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AAAInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AAAInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AAAInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AAAInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDOCUMENTACION;
    private javax.swing.JButton jButtonPROBLEMAS;
    private javax.swing.JLabel jLabelENCABEZADO;
    private javax.swing.JLabel jLabelFONDO;
    private javax.swing.JLabel jLabelFONDO_IZQ;
    private javax.swing.JLabel jLabelGRADO;
    private javax.swing.JLabel jLabelautor;
    private javax.swing.JLabel jLabelcursoacademico;
    private javax.swing.JLabel jLabeletsiinf;
    private javax.swing.JLabel jLabeltfg;
    private javax.swing.JLabel jLabeltitulo;
    private javax.swing.JLabel jLabeltitulo2;
    private javax.swing.JLabel jLabeltutor;
    // End of variables declaration//GEN-END:variables
}
