/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AAAALanzador;

import Cenicienta.EnunciadoCenicienta;
import LlenandoPiscinas.*;
import CodigosDeBarras.*;
import LaTiendaDeLaEsquina.*;
import LosProblemasDeSerRico.EnunciadoLosProblemasDeSerRico;
import MichaelJFox.EnunciadoMichaelJFox;
/**
 *
 * @author maxxi
 */
public class Problemas extends javax.swing.JFrame {

    
    public Problemas() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonLlenandoPiscinas = new javax.swing.JButton();
        jButtontiendaesquina = new javax.swing.JButton();
        jButtoncenicienta = new javax.swing.JButton();
        jButtonCodigosDeBarras = new javax.swing.JButton();
        jLabelExpresiones = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonLlenandoPiscinas1 = new javax.swing.JButton();
        jButtonDOCUMENTACION = new javax.swing.JButton();
        jButtonPROBLEMAS = new javax.swing.JButton();
        jLabelENCABEZADO = new javax.swing.JLabel();
        jLabelFONDO_IZQ = new javax.swing.JLabel();
        jLabelFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1030, 600));
        setMinimumSize(new java.awt.Dimension(1030, 600));
        setPreferredSize(new java.awt.Dimension(1030, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Bucles");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jButton2.setText("Michael J. Fox y el Pato Donald");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 250, 30));

        jButton1.setText("Los problemas de ser rico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 220, 30));

        jButtonLlenandoPiscinas.setText("Llenando piscinas");
        jButtonLlenandoPiscinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLlenandoPiscinasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLlenandoPiscinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 150, 30));

        jButtontiendaesquina.setText("La tienda de la esquina");
        jButtontiendaesquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontiendaesquinaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtontiendaesquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 200, 30));

        jButtoncenicienta.setText("El baile de Cenicienta");
        jButtoncenicienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncenicientaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoncenicienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 190, 30));

        jButtonCodigosDeBarras.setText("Códigos de barras");
        jButtonCodigosDeBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCodigosDeBarrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCodigosDeBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 150, 30));

        jLabelExpresiones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelExpresiones.setText("Expresiones");
        getContentPane().add(jLabelExpresiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Condicionales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jButtonLlenandoPiscinas1.setText("Llenando piscinas");
        jButtonLlenandoPiscinas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLlenandoPiscinas1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLlenandoPiscinas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 150, 30));

        jButtonDOCUMENTACION.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDOCUMENTACION.setForeground(new java.awt.Color(0, 153, 153));
        jButtonDOCUMENTACION.setText("Documentación");
        jButtonDOCUMENTACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDOCUMENTACIONActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDOCUMENTACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 40));

        jButtonPROBLEMAS.setBackground(new java.awt.Color(204, 204, 204));
        jButtonPROBLEMAS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPROBLEMAS.setForeground(new java.awt.Color(0, 153, 153));
        jButtonPROBLEMAS.setText("Problemas");
        jButtonPROBLEMAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPROBLEMASActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPROBLEMAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        jLabelENCABEZADO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde oscuro.jpg"))); // NOI18N
        getContentPane().add(jLabelENCABEZADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jLabelFONDO_IZQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde clarito.jpg"))); // NOI18N
        getContentPane().add(jLabelFONDO_IZQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 730, 60));
        getContentPane().add(jLabelFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPROBLEMASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPROBLEMASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPROBLEMASActionPerformed

    private void jButtonCodigosDeBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCodigosDeBarrasActionPerformed
        // TODO add your handling code here:
        EnunciadoCodigodeBarras a= new EnunciadoCodigodeBarras();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCodigosDeBarrasActionPerformed

    private void jButtonLlenandoPiscinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLlenandoPiscinasActionPerformed
        // TODO add your handling code here:
        EnunciadoLlenandoPiscinas a= new EnunciadoLlenandoPiscinas();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLlenandoPiscinasActionPerformed

    private void jButtonDOCUMENTACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDOCUMENTACIONActionPerformed
        // TODO add your handling code here:
        Documentacion a= new Documentacion();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDOCUMENTACIONActionPerformed

    private void jButtonLlenandoPiscinas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLlenandoPiscinas1ActionPerformed
        // TODO add your handling code here:
        EnunciadoLlenandoPiscinas a= new EnunciadoLlenandoPiscinas();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLlenandoPiscinas1ActionPerformed

    private void jButtontiendaesquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontiendaesquinaActionPerformed
        // TODO add your handling code here:
        EnunciadoLaTiendaDeLaEsquina a= new EnunciadoLaTiendaDeLaEsquina();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtontiendaesquinaActionPerformed

    private void jButtoncenicientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncenicientaActionPerformed
        // TODO add your handling code here:
        EnunciadoCenicienta a= new EnunciadoCenicienta();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtoncenicientaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EnunciadoLosProblemasDeSerRico a= new EnunciadoLosProblemasDeSerRico();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        EnunciadoMichaelJFox a= new EnunciadoMichaelJFox();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problemas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCodigosDeBarras;
    private javax.swing.JButton jButtonDOCUMENTACION;
    private javax.swing.JButton jButtonLlenandoPiscinas;
    private javax.swing.JButton jButtonLlenandoPiscinas1;
    private javax.swing.JButton jButtonPROBLEMAS;
    private javax.swing.JButton jButtoncenicienta;
    private javax.swing.JButton jButtontiendaesquina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelENCABEZADO;
    private javax.swing.JLabel jLabelExpresiones;
    private javax.swing.JLabel jLabelFONDO;
    private javax.swing.JLabel jLabelFONDO_IZQ;
    // End of variables declaration//GEN-END:variables
}
