/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sudokus;





import AAAALanzador.Documentacion;
import AAAALanzador.Problemas;
import static Sudokus.EntregaSudokus.filename;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author maxxi
 */
public class EntregaSudokus extends javax.swing.JFrame {

    public static String filename;
    
    
    public EntregaSudokus() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAutores = new javax.swing.JLabel();
        jButtonDOCUMENTACION = new javax.swing.JButton();
        jButtonREALIZARENTREGA = new javax.swing.JButton();
        jButtonPATH = new javax.swing.JButton();
        jTextFieldPATH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRESULTADO = new javax.swing.JTextArea();
        jButtonPROBLEMAS = new javax.swing.JButton();
        jButtonENUNCIADO = new javax.swing.JButton();
        jButtonEJEMPLOS = new javax.swing.JButton();
        jButtonCREDITOS = new javax.swing.JButton();
        jButtonENVIAR = new javax.swing.JButton();
        jLabelTIEMPO = new javax.swing.JLabel();
        jLabelNOMBRE_EJERCICIO = new javax.swing.JLabel();
        jLabelENCABEZADO = new javax.swing.JLabel();
        jLabelFONDO_IZQ = new javax.swing.JLabel();
        jLabelFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1030, 600));
        setMinimumSize(new java.awt.Dimension(1030, 600));
        setPreferredSize(new java.awt.Dimension(1030, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAutores.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAutores.setText("Seleccione su codigo");
        getContentPane().add(jLabelAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jButtonDOCUMENTACION.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDOCUMENTACION.setForeground(new java.awt.Color(0, 153, 153));
        jButtonDOCUMENTACION.setText("Documentación");
        jButtonDOCUMENTACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDOCUMENTACIONActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDOCUMENTACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 40));

        jButtonREALIZARENTREGA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonREALIZARENTREGA.setText("Entregar");
        jButtonREALIZARENTREGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREALIZARENTREGAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonREALIZARENTREGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 170, 50));

        jButtonPATH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPATH.setText("Buscar");
        jButtonPATH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPATHActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPATH, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 110, 30));
        getContentPane().add(jTextFieldPATH, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 620, 30));

        jTextAreaRESULTADO.setColumns(20);
        jTextAreaRESULTADO.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRESULTADO);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 990, 290));

        jButtonPROBLEMAS.setBackground(new java.awt.Color(204, 204, 204));
        jButtonPROBLEMAS.setForeground(new java.awt.Color(0, 153, 153));
        jButtonPROBLEMAS.setText("Problemas");
        jButtonPROBLEMAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPROBLEMASActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPROBLEMAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        jButtonENUNCIADO.setText("Enunciado");
        jButtonENUNCIADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonENUNCIADOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonENUNCIADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 120, 40));

        jButtonEJEMPLOS.setText("Ejemplos");
        jButtonEJEMPLOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEJEMPLOSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEJEMPLOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 130, 40));

        jButtonCREDITOS.setText("Créditos");
        jButtonCREDITOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCREDITOSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCREDITOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 130, 40));

        jButtonENVIAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonENVIAR.setText("Enviar");
        jButtonENVIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonENVIARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonENVIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 130, 40));

        jLabelTIEMPO.setBackground(new java.awt.Color(0, 153, 153));
        jLabelTIEMPO.setText("Tiempo máximo: 2,000 s                             ");
        getContentPane().add(jLabelTIEMPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 450, -1));

        jLabelNOMBRE_EJERCICIO.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNOMBRE_EJERCICIO.setText("SUDOKUS CORRECTOS");
        getContentPane().add(jLabelNOMBRE_EJERCICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 500, 40));

        jLabelENCABEZADO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde oscuro.jpg"))); // NOI18N
        getContentPane().add(jLabelENCABEZADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jLabelFONDO_IZQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde clarito.jpg"))); // NOI18N
        getContentPane().add(jLabelFONDO_IZQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 730, 60));
        getContentPane().add(jLabelFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 990, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonENVIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonENVIARActionPerformed
       
       

    }//GEN-LAST:event_jButtonENVIARActionPerformed

    private void jButtonEJEMPLOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEJEMPLOSActionPerformed
        EjemplosSudokus a= new EjemplosSudokus();
        a.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonEJEMPLOSActionPerformed

    private void jButtonCREDITOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCREDITOSActionPerformed
        // TODO add your handling code here:
         CreditosSudokus a= new CreditosSudokus();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCREDITOSActionPerformed

    private void jButtonPROBLEMASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPROBLEMASActionPerformed
        // TODO add your handling code here:
        Problemas a= new Problemas();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPROBLEMASActionPerformed

    private void jButtonENUNCIADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonENUNCIADOActionPerformed
        // TODO add your handling code here:
        EnunciadoSudokus a= new EnunciadoSudokus();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonENUNCIADOActionPerformed

    private void jButtonPATHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPATHActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser= new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        jTextFieldPATH.setText(filename);
    }//GEN-LAST:event_jButtonPATHActionPerformed

    private void jButtonREALIZARENTREGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREALIZARENTREGAActionPerformed
        // TODO add your handling code here:
        //Variables primera prueba


        String[] prueba1={"1","4 1 3 8 2 5 6 7 9 ","5 6 7 1 4 9 8 3 2 ","2 8 9 7 3 6 1 4 5 ","1 9 5 4 6 2 7 8 3 ","7 2 6 9 8 3 5 1 4 ","3 4 8 5 1 7 2 9 6 ","8 5 1 6 9 4 3 2 7 ","9 7 2 3 5 8 4 6 1 ","6 3 4 2 7 1 9 5 8 "};
        String esperado1="SI ";
        //Variables segunda prueba
        String[] prueba2= {"1","4 1 3 8 2 5 6 7 9 ","5 6 7 1 4 9 8 3 2 ","2 8 9 7 3 6 1 4 5 ","1 9 5 4 6 2 7 8 3 ","7 2 6 9 8 3 5 1 4 ","3 4 8 5 1 7 2 9 6 ","8 5 1 6 9 4 3 2 7 ","9 7 2 3 5 8 4 6 8 ","6 3 4 2 7 1 9 5 1 "};
        String esperado2="NO ";
        //Variables tercera prueba
        String[] prueba3={"1","4 1 3 8 2 5 6 7 9 ","5 6 7 1 4 9 8 3 2 ","2 8 9 7 3 6 1 4 5 ","1 9 5 4 6 2 7 8 3 ","7 2 6 9 8 3 5 1 4 ","3 4 8 5 1 7 2 9 6 ","8 5 1 6 9 4 2 3 7 ","9 7 2 3 5 8 4 6 1 ","6 3 4 2 7 1 9 5 8 "};
        String esperado3="NO ";
        //Variables cuarta prueba
        String[] prueba4= {"1","4 1 3 8 2 5 6 7 9 ","5 6 7 1 4 9 8 3 2 ","2 8 9 7 3 6 1 4 5 ","1 9 5 4 6 2 7 8 3 ","7 2 6 9 8 3 5 1 4 ","6 3 4 2 7 1 9 5 8 ","8 5 1 6 9 4 3 2 7 ","9 7 2 3 5 8 4 6 1 ","3 4 8 5 1 7 2 9 6 "};
        String esperado4="NO ";
        
        //Variables quinta prueba
        String[] prueba5={"1","4 1 3 8 2 5 6 7 9 ","5 6 7 1 4 9 8 3 2 ","2 8 9 7 3 6 1 4 5 ","1 9 5 4 6 2 7 8 3 ","7 2 6 9 8 3 5 1 4 ","3 4 8 5 1 7 2 9 6 ","8 5 1 6 9 4 3 2 7 ","9 7 2 3 5 8 4 6 1 ","6 3 4 2 7 1 9 5 8 ","4 1 3 8 2 5 6 7 9 ","5 6 7 1 4 9 8 3 2 ","2 8 9 7 3 6 1 4 5 ","1 9 5 4 6 2 7 8 3 ","7 2 6 9 8 3 5 1 4 ","6 3 4 2 7 1 9 5 8 ","8 5 1 6 9 4 3 2 7 ","9 7 2 3 5 8 4 6 1 ","3 4 8 5 1 7 2 9 6 "};
        String esperadoW5="SI  ";
        String esperadoU5="SI ";
       
    // PRIMERO COMPROBAMOS QUE EL ALUMNO HAYA SELECCIONADO SU CODIGO    
        if(filename!=null){
            String so=EjecutadorSudokus.SistemaOperativo(filename);
            if("windows".equals(so)){
            
            jTextAreaRESULTADO.setText(null);
    // INSTANCIAMOS UN OBJETO DE LA CLASE EJECUTADOR PARA PODER TENER ACCESO A LOS METODOS QUE NECESITAREMOS PARA LAS REALIZAR LAS PRUEBAS        
            EjecutadorSudokus objeto= new EjecutadorSudokus();
    // COMPROBAMOS QUE EL CODIGO DEL ALUMNO PUEDA COMPILARSE CORRECTAMENTE        
            
            String compilacion=objeto.compilador(filename);
            jTextAreaRESULTADO.append("----PRUEBA DE CORRECTA COMPILACIÓN DEL CODIGO---"+"\n");
            jTextAreaRESULTADO.append(compilacion+"\n"+"\n");
            
            
            if(compilacion=="Correcto"){
                String resultadoprueba="";
    //PRIMERA PRUEBA
                jTextAreaRESULTADO.append("----PRUEBA CON EL CASO DESCRITO EN EL ENUNCIADO---"+"\n");
                resultadoprueba=RobotWindows(filename,prueba1,esperado1,2000);
    //SI SUPERA LA PRUEBA, SEGUIMOS REALIZANDO PRUEBAS. EN CASO CONTRARIO NO HACE FALTA SEGUIR, EL CODIGO DEL ALUMNO YA ESTA MAL.          
                if(resultadoprueba.equals("Correcto")){
    
    //SEGUNDA PRUEBA
                    
                    jTextAreaRESULTADO.append("----PRUEBA EN LA QUE FALLA LA SUMA HORIZONTAL DE UNA DE LAS FILAS---"+"\n");
                    resultadoprueba=RobotWindows(filename,prueba2,esperado2,2000);
                    if(resultadoprueba.equals("Correcto")){
    //TERCERA PRUEBA
                        jTextAreaRESULTADO.append("----PRUEBA EN LA QUE FALLA LA SUMA VERTICAL DE UNA DE LAS COLUMNAS---"+"\n");
                        resultadoprueba=RobotWindows(filename,prueba3,esperado3,2000);
                        if(resultadoprueba.equals("Correcto")){
    //CUARTA PRUEBA                        
                            jTextAreaRESULTADO.append("----PRUEBA EN LA QUE FALLA LA SUMA DE UNA DE LAS 9 REGIONES DE DIMENSIÓN 3X3---"+"\n");
                            resultadoprueba=RobotWindows(filename,prueba4,esperado4,2000);
                            if(resultadoprueba.equals("Correcto")){
                            
    //QUINTA PRUEBA
                            jTextAreaRESULTADO.append("----PRUEBA DE TERMINACIÓN CUANDO DICTA EL ENUNCIADO---"+"\n");
                            resultadoprueba=RobotWindows(filename,prueba5,esperadoW5,2000);
                            if(resultadoprueba.equals("Correcto")){
                                jTextAreaRESULTADO.append("----VEREDICTO FINAL----"+"\n");
                                jTextAreaRESULTADO.append("Enhorabuena, tu codigo es correcto"+"\n"+"\n");
                            }
                           
                        }
                    }
                }
            }
        }
            
        
        }
            else if("ubuntu".equals(so)){
            
            jTextAreaRESULTADO.setText(null);
    // INSTANCIAMOS UN OBJETO DE LA CLASE EJECUTADOR PARA PODER TENER ACCESO A LOS METODOS QUE NECESITAREMOS PARA LAS REALIZAR LAS PRUEBAS        
            EjecutadorSudokus objeto= new EjecutadorSudokus();
    // COMPROBAMOS QUE EL CODIGO DEL ALUMNO PUEDA COMPILARSE CORRECTAMENTE        
            
            String compilacion=objeto.compilador(filename);
            jTextAreaRESULTADO.append("----PRUEBA DE CORRECTA COMPILACION DEL CODIGO---"+"\n");
            jTextAreaRESULTADO.append(compilacion+"\n"+"\n");
            
            
            if(compilacion=="Correcto"){
                String resultadoprueba="";
    //PRIMERA PRUEBA
                jTextAreaRESULTADO.append("----PRUEBA CON EL CASO DESCRITO EN EL ENUNCIADO---"+"\n");
                resultadoprueba=RobotUbuntu(filename,prueba1,esperado1,2000);
    //SI SUPERA LA PRUEBA, SEGUIMOS REALIZANDO PRUEBAS. EN CASO CONTRARIO NO HACE FALTA SEGUIR, EL CODIGO DEL ALUMNO YA ESTA MAL.          
                if(resultadoprueba.equals("Correcto")){
    
    //SEGUNDA PRUEBA
                    
                    jTextAreaRESULTADO.append("----PRUEBA EN LA QUE FALLA LA SUMA HORIZONTAL DE UNA DE LAS FILAS---"+"\n");
                    resultadoprueba=RobotUbuntu(filename,prueba2,esperado2,2000);
                    if(resultadoprueba.equals("Correcto")){
    //TERCERA PRUEBA
                        jTextAreaRESULTADO.append("----PRUEBA EN LA QUE FALLA LA SUMA VERTICAL DE UNA DE LAS COLUMNAS--"+"\n");
                        resultadoprueba=RobotUbuntu(filename,prueba3,esperado3,2000);
                        if(resultadoprueba.equals("Correcto")){
    //CUARTA PRUEBA                        
                            jTextAreaRESULTADO.append("----PRUEBA EN LA QUE FALLA LA SUMA DE UNA DE LAS 9 REGIONES DE DIMENSIÓN 3X3---"+"\n");
                            resultadoprueba=RobotWindows(filename,prueba4,esperado4,2000);
                            if(resultadoprueba.equals("Correcto")){
    //QUINTA PRUEBA                            
                                jTextAreaRESULTADO.append("----PRUEBA DE TERMINACION CUANDO DICTA EL ENUNCIADO---"+"\n");
                                resultadoprueba=RobotWindows(filename,prueba5,esperadoU5,5000);
                                if(resultadoprueba.equals("Correcto")){
                                    jTextAreaRESULTADO.append("----VEREDICTO FINAL----"+"\n");
                                    jTextAreaRESULTADO.append("Enhorabuena, tu codigo es correcto"+"\n"+"\n");
                                }
                           
                            }
                        }
                    }
                    
                }
            }
            
        
            }
            else{
                jTextAreaRESULTADO.append("----VEREDICTO FINAL----"+"\n");    
                jTextAreaRESULTADO.append("Sistema operativo incompatible"+"\n"+"\n");
            }
            
            }
             
        else{
        jTextAreaRESULTADO.append("----VEREDICTO FINAL----"+"\n");    
        jTextAreaRESULTADO.append("Aun no has seleccionado ningun archivo"+"\n"+"\n");}
    }//GEN-LAST:event_jButtonREALIZARENTREGAActionPerformed

    private void jButtonDOCUMENTACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDOCUMENTACIONActionPerformed
        // TODO add your handling code here:
        Documentacion a= new Documentacion();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDOCUMENTACIONActionPerformed
    private String RobotWindows(String ruta,String[] prueba,String esperado, int time){
        String resultado="error";
        String resultadoprueba="";
       
        resultadoprueba=EjecutadorSudokus.runFileWindows(ruta,prueba,time);
                
                if(resultadoprueba.equals(esperado)){  
                  jTextAreaRESULTADO.append("Correcto"+"\n"+"\n");
                  resultado="Correcto";
    
               }
                else if (resultadoprueba.equals("Tiempo limite excedido")){
                    EjecutadorSudokus.matarHijosWindows();
                    jTextAreaRESULTADO.append("Tiempo limite excedido"+"\n"+"\n");
                    jTextAreaRESULTADO.append("----VEREDICTO FINAL---"+"\n");
                    jTextAreaRESULTADO.append("Tu codigo no es correcto"+"\n"+"\n");
                    
                }
                else if (resultadoprueba.equals("Bucle infinito")){
                    EjecutadorSudokus.matarHijosWindows();
                    jTextAreaRESULTADO.append("Bucle infinito"+"\n"+"\n");
                    jTextAreaRESULTADO.append("----VEREDICTO FINAL---"+"\n");
                    jTextAreaRESULTADO.append("Tu codigo no es correcto"+"\n"+"\n");
                    
                }
                else{
                    
                    
                    jTextAreaRESULTADO.append("Resultado incorrecto"+"\n"+"\n");
                    jTextAreaRESULTADO.append("----VEREDICTO FINAL---"+"\n");
                    jTextAreaRESULTADO.append("Tu codigo no es correcto"+"\n"+"\n");
                }
        return resultado;
    }
    private String RobotUbuntu(String ruta,String[] prueba,String esperado, int time){
        String resultado="error";
        String resultadoprueba="";
        ;
        resultadoprueba=EjecutadorSudokus.runFileUbuntu(ruta,prueba,time);
                
                if(resultadoprueba.equals(esperado)){  
                  jTextAreaRESULTADO.append("Correcto"+"\n"+"\n");
                  resultado="Correcto";
    
               }
                else if (resultadoprueba.equals("Tiempo limite excedido")){
                    
                    jTextAreaRESULTADO.append("Tiempo limite excedido"+"\n"+"\n");
                    jTextAreaRESULTADO.append("----VEREDICTO FINAL---"+"\n");
                    jTextAreaRESULTADO.append("Tu codigo no es correcto"+"\n"+"\n");
                    
                }
                else if (resultadoprueba.equals("Bucle infinito")){
                    
                    jTextAreaRESULTADO.append("Bucle infinito"+"\n"+"\n");
                    jTextAreaRESULTADO.append("----VEREDICTO FINAL---"+"\n");
                    jTextAreaRESULTADO.append("Tu codigo no es correcto"+"\n"+"\n");
                    
                }
                else{
                    
                    
                    jTextAreaRESULTADO.append("Resultado incorrecto"+"\n"+"\n");
                    jTextAreaRESULTADO.append("----VEREDICTO FINAL---"+"\n");
                    jTextAreaRESULTADO.append("Tu codigo no es correcto"+"\n"+"\n");
                }
        return resultado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntregaSudokus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCREDITOS;
    private javax.swing.JButton jButtonDOCUMENTACION;
    private javax.swing.JButton jButtonEJEMPLOS;
    private javax.swing.JButton jButtonENUNCIADO;
    private javax.swing.JButton jButtonENVIAR;
    private javax.swing.JButton jButtonPATH;
    private javax.swing.JButton jButtonPROBLEMAS;
    private javax.swing.JButton jButtonREALIZARENTREGA;
    private javax.swing.JLabel jLabelAutores;
    private javax.swing.JLabel jLabelENCABEZADO;
    private javax.swing.JLabel jLabelFONDO;
    private javax.swing.JLabel jLabelFONDO_IZQ;
    private javax.swing.JLabel jLabelNOMBRE_EJERCICIO;
    private javax.swing.JLabel jLabelTIEMPO;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaRESULTADO;
    private javax.swing.JTextField jTextFieldPATH;
    // End of variables declaration//GEN-END:variables
}
